In [1]:
import csv 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import time


In [2]:
try:
    data_full = pd.read_csv("trainset.csv", index_col=1)
    print("Data loaded")
except FileNotFoundError:
    print("Hey! The file was not found. Check again!")
from sklearn import preprocessing   

Data loaded


In [3]:
dataXTr = data_full.iloc[0:11706]
dataXTs = data_full.iloc[9656:11706]

In [4]:
dataXTr = dataXTr[dataXTr.label != 'Draw']
dataXTs = dataXTs[dataXTs.label != 'Draw']
dataXTsv = dataXTs
dataXTr
label_df = dataXTr.iloc[:,-1]
label = (label_df).tolist()
label_dft = dataXTs.iloc[:,-1]
labelt = (label_dft).tolist()

In [5]:
for i in range(len(label)):
    if (label[i] == 'Win'):
        label[i] = 1
    if (label[i] == 'Defeat'):
        label[i] = -1
        
        
label
Y = np.array(label)
Y = Y.reshape(dataXTr.shape[0],1)
Y

array([[ 1],
       [-1],
       [ 1],
       ...,
       [-1],
       [-1],
       [-1]])

In [6]:
#dropping last column 'label'
dataX = dataXTr.drop(['label'], axis = 1)
dataXTs = dataXTs.drop(['label'], axis = 1)

In [7]:
min_max_sc = preprocessing.MinMaxScaler()
dataX = pd.DataFrame(min_max_sc.fit_transform(dataX))
dataX

0         1    2    3         4         5    6    7    8    9   \
0      0.000000  0.396825  0.0  0.0  0.000000  0.000000  1.0  0.0  0.0  0.0   
1      0.000085  0.396825  0.0  0.0  0.000000  0.000000  1.0  0.0  0.0  0.0   
2      0.000171  0.396825  0.0  0.0  0.000000  0.000000  1.0  0.0  0.0  0.0   
3      0.000256  0.428571  0.1  0.1  0.000000  0.000000  1.0  0.0  0.0  0.0   
4      0.000342  0.365079  0.0  0.0  0.000000  0.000000  1.0  0.0  0.0  0.0   
...         ...       ...  ...  ...       ...       ...  ...  ...  ...  ...   
11701  0.999658  0.301587  0.9  0.2  0.666667  0.000000  0.0  0.0  0.0  0.0   
11702  0.999744  0.333333  0.2  0.3  0.000000  0.666667  0.0  0.0  0.0  0.0   
11703  0.999829  0.380952  0.2  0.3  0.333333  0.000000  0.0  0.0  0.0  0.0   
11704  0.999915  0.428571  0.3  0.5  0.000000  0.333333  0.0  0.0  0.0  0.0   
11705  1.000000  0.650794  0.2  0.8  0.000000  1.000000  0.0  0.0  0.0  0.0   

       ...        35        36        37        38        39        40  \
0      ...  0.444444  0.533333  0.551020  0.386364  0.308862  0.449449   
1      ...  0.511111  0.466667  0.653061  0.500000  0.324207  0.469354   
2      ...  0.466667  0.200000  0.346939  0.409091  0.720847  0.306356   
3      ...  0.644444  0.622222  0.591837  0.522727  0.186794  0.412104   
4      ...  0.422222  0.200000  0.346939  0.227273  0.584209  0.400592   
...    ...       ...       ...       ...       ...       ...       ...   
11701  ...  0.422222  0.511111  0.469388  0.340909  0.833289  0.194925   
11702  ...  0.444444  0.600000  0.551020  0.545455  0.339960  0.464714   
11703  ...  0.355556  0.377778  0.387755  0.545455  0.462100  0.448241   
11704  ...  0.533333  0.555556  0.510204  0.409091  0.342140  0.486984   
11705  ...  0.533333  0.644444  0.632653  0.727273  0.056138  0.259120   

             41        42        43        44  
0      0.468897  0.313154  0.475749  0.474753  
1      0.441540  0.292528  0.524076  0.470514  
2      0.118603  0.746849  0.353522  0.089764  
3      0.617908  0.176174  0.464266  0.622912  
4      0.208252  0.617137  0.442370  0.177176  
...         ...       ...       ...       ...  
11701  0.064043  0.823543  0.205803  0.088562  
11702  0.427675  0.385209  0.471763  0.402134  
11703  0.309108  0.470611  0.461808  0.318838  
11704  0.412761  0.385209  0.471763  0.402134  
11705  0.841493  0.085321  0.267367  0.821563  

[11706 rows x 45 columns]

In [8]:
X_arr = dataX.values
M = np.zeros((X_arr.shape[1],1))

In [9]:
def logistic_func(m,x):
    return 1.0/(1 + np.exp(-np.dot(X_arr, m))) 
logistic_func(M,X_arr)

array([[0.5],
       [0.5],
       [0.5],
       ...,
       [0.5],
       [0.5],
       [0.5]])

In [10]:
def log_gradient(m, X, y): 
    ''' 
    logistic gradient function 
    '''
    first_calc = logistic_func(m, X) - y.reshape(X.shape[0], -1) 
    final_calc = np.dot(first_calc.T, X) 
    return final_calc.T 
log_gradient(M, X_arr, Y)

array([[1605.03695002],
       [1593.48412698],
       [ 623.55      ],
       [1637.9       ],
       [ 225.66666667],
       [1469.16666667],
       [ 232.5       ],
       [ 594.5       ],
       [ 513.5       ],
       [ 538.        ],
       [ 477.5       ],
       [ 407.        ],
       [   0.        ],
       [ 290.        ],
       [  86.        ],
       [   0.        ],
       [   0.        ],
       [1841.38297872],
       [1384.30769231],
       [1693.76136364],
       [1513.30952381],
       [1834.84545455],
       [1532.75      ],
       [1607.75      ],
       [1639.4       ],
       [1621.72222222],
       [1661.43181818],
       [1680.93181818],
       [2210.53658537],
       [2206.26190476],
       [2247.63636364],
       [2176.53409091],
       [2322.63207547],
       [2105.67777778],
       [2175.38636364],
       [2197.95555556],
       [2169.31111111],
       [2349.48979592],
       [2241.69318182],
       [ 452.03931519],
       [1480.14182715],
       [1974.474

In [12]:
def cost_func(m, X, y): 
    ''' 
    cost function, J 
    '''
    log_func_v = logistic_func(m, X) 
    #y = np.squeeze(y) 
    step1 = y * np.log(log_func_v) 
    step2 = (1 - y) * np.log(1 - log_func_v) 
    final = -step1 - step2 
    return np.mean(final) 
cost_func(M,X_arr,Y)

0.6931471805599453

In [13]:
def grad_desc(X, y, m, lr=.01, converge_change=.001): 
    ''' 
    gradient descent function 
    '''
    cost = cost_func(m, X, y) 
    change_cost = 1
    num_iter = 1
      
    while(change_cost > converge_change): 
        old_cost = cost 
        m = m - (lr * log_gradient(m, X, y)) 
        cost = cost_func(m, X, y) 
        change_cost = old_cost - cost 
        num_iter += 1
      
    return m, num_iter  


In [65]:
M, num_iter = grad_desc(X_arr, Y, M, lr=1, converge_change=0.01)
def pred_values(m, x): 
    ''' 
    function to predict labels 
    '''
    
    pred_prob = logistic_func(m, x)
    np.savetxt("foo.csv", M, delimiter=",")
    pred_value = np.where(pred_prob >= .5, 1, -1)
    return pred_value 
yp = pred_values(M, X_arr)
np.sum(Y==yp)

/home/mayank/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
/home/mayank/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
/home/mayank/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in multiply
  


8253

In [66]:
def plot_reg(X, y, m): 
    ''' 
    function to plot decision boundary 
    '''
    # labelled observations 
    x_0 = X[np.where(y == 1.0)] 
    x_1 = X[np.where(y == -1.0)] 
      
    # plotting points with diff color for diff label 
    plt.scatter([x_0[1,:]], [x_0[2,:]], c='b', label='y = 0') 
    plt.scatter([x_1[1,:]], [x_1[2,:]], c='r', label='y = 1') 
      
    # plotting decision boundary 
#     x1 = np.arange(0, 1, 0.1) 
#     x2 = -(m[0,0] + m[0,1]*x1)/m[0,2] 
#     plt.plot(x1, x2, c='k', label='reg line') 
  
    plt.xlabel('x1') 
    plt.ylabel('x2') 
    plt.legend() 
    plt.show() 
plot_reg(X_arr,Y,M)

IndexError: too many indices for array

In [122]:
# if __name__ == "__main__": 
#     # load the dataset 
#     dataset = loadCSV('dataset1.csv') 
      
#     # normalizing feature matrix 
#     X = normalize(dataset[:, :-1]) 
      
#     # stacking columns wth all ones in feature matrix 
#     X = np.hstack((np.matrix(np.ones(X.shape[0])).T, X)) 
  
#     # response vector 
#     y = dataset[:, -1] 
  
#     # initial beta values 
#     beta = np.matrix(np.zeros(X.shape[1])) 
  
#     # beta values after running gradient descent 
#     beta, num_iter = grad_desc(X, y, beta) 
  
#     # estimated beta values and number of iterations 
#     print("Estimated regression coefficients:", beta) 
#     print("No. of iterations:", num_iter) 
  
#     # predicted labels 
#     y_pred = pred_values(beta, X) 
      
#     # number of correctly predicted labels 
#     print("Correctly predicted labels:", np.sum(y == y_pred)) 
      
#     # plotting regression line 
#     plot_reg(X, y, beta) 

ValueError: could not convert string to float: 'Win'